version: "2"

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: mac-cleanup-go
    goimports:
      local-prefixes:
        - mac-cleanup-go

linters:
  enable:
    # Code quality
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - revive
    - unconvert
    - unparam
    - wastedassign

    # Security
    - gosec

    # Performance
    - copyloopvar
    - bodyclose

    # Style
    - misspell
    - whitespace

    # Error handling
    - errorlint

  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true
        - name: if-return
        - name: increment-decrement
        - name: var-naming
          disabled: true
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code

    gosec:
      excludes:
        - G104
        - G204  # command execution from config (trusted source)
        - G301  # directory permissions 0755 is fine
        - G306  # file permissions 0644 is fine

    errorlint:
      errorf: true
      asserts: true
      comparison: true

  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    paths:
      - vendor
    rules:
      - path: "_test\\.go$"
        linters:
          - gosec
          - errcheck

