coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 50%

comment:
  layout: "header, diff, footer"
  require_changes: true

ignore:
  - "main.go"
  - "scripts/"
